# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'CQRS Build Process'
  jobs:
  - job: BuildCqrsExemplo
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
- stage: Test
  displayName: 'Testing Process'
  jobs:
  - job: TestCqrsExemplo
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: dotnet test --no-build --no-restore
        displayName: 'dotnet test'