# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: CQRS Build Process
  jobs:
  - job: BuildCqrsExemplo
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
- stage: Test
  displayName: Testing Process
  jobs:
  - job: TestCqrsExemplo    
    steps:
      - script: dotnet test --no-build --no-restore
        displayName: 'dotnet test'
